defmodule Mix.Tasks.Lcars.Topology do
  use Boundary, classify_to: Fleet.Application

  @shortdoc "Regenerates (or --check) the boundary topology map in lib/fleet/README.md"

  @moduledoc """
  Boundary topology map — derives the layered view of the fleet from the `use Boundary`
  declarations (the single source of truth of the dependency structure; the compiler
  enforces it, this task only PROJECTS it) and writes it as a markdown table between
  markers in `lib/fleet/README.md`.

  Height is mechanical: `H(domain) = 1 + max(H(deps))`, 0 for `deps: []` (a DAG —
  boundary forbids cycles — always induces this ladder). The layer NAMES are editorial
  and live in ONE place: `@layers` below. A new or moved domain without a matching
  entry fails the check — changing floor is a conscious, reviewed event, never silent.

  ## Usage

      mix lcars.topology            # regenerate the section in lib/fleet/README.md
      mix lcars.topology --check    # exit 1 if the committed map diverges (gate step)
  """

  use Mix.Task

  @recursive false

  @readme "lib/fleet/README.md"
  @root_readme "README.md"
  @begin_marker "<!-- boundary-topology:begin (generated by `mix lcars.topology` — do not edit by hand) -->"
  @end_marker "<!-- boundary-topology:end -->"

  # UPWARD runtime seams (config-injected, compile-INVISIBLE — they cannot be derived from
  # the boundary declarations, which is the point: boundary forbids the literal edge). Declared
  # here so the generated diagram can draw them dotted; the contract lives in CLAUDE.md § Seams.
  # NOT listed: injection seams over an EXISTING compile dep (`:coord_backend`, `:launch_backend`)
  # — those swap an implementation for hermeticity, they do not cross a forbidden edge.
  @seams [
    {"Fleet.Spawner", "Fleet.MCP", ":mcp_socket_provisioner"},
    {"Fleet.MCP", "Fleet.Pilot", ":forge_client / :project_onboard"}
  ]

  # Editorial layer names — the ONLY place they are declared. Keys are domain module
  # names as declared in `use Boundary`. "foundation" is the one mechanically checkable
  # name (deps: []); the others are a reading, kept honest by living here alone.
  @layers %{
    "Fleet.Slug" => "foundation",
    "Fleet.EnvParse" => "foundation",
    "Fleet.GitRef" => "foundation",
    "Fleet.Layout" => "foundation",
    "Fleet.Event" => "foundation",
    "Fleet.SchemaCache" => "foundation",
    "Fleet.Labels" => "foundation",
    "Fleet.Decision" => "foundation",
    "Fleet.Shutdown.Quiesce" => "foundation",
    "Fleet.EventRouter" => "substrate",
    "Fleet.CapProfile" => "substrate",
    "Fleet.Credentials" => "pod primitives",
    "Fleet.TaskQueue" => "pod primitives",
    "Fleet.SPBuilder" => "pod primitives",
    "Fleet.Coord" => "pod primitives",
    "Fleet.ProjectBootstrap" => "pod composition",
    "Fleet.Spawner" => "pod composition",
    "Fleet.Workflow" => "work",
    "Fleet.MCP" => "work",
    "Fleet.Observation" => "surface",
    "Fleet.Pilot" => "steering",
    "Fleet.Starfleet" => "steering",
    "Fleet.API" => "surface",
    "Fleet.Application" => "OTP root"
  }

  @impl Mix.Task
  def run(args) do
    check? = "--check" in args

    graph = parse_boundaries()
    outputs = [{@readme, render_section(compute_heights(graph))}, {@root_readme, render_mermaid(graph)}]

    if check? do
      stale =
        for {file, section} <- outputs, extract_section(File.read!(file)) != section, do: file

      if stale == [] do
        Mix.shell().info("topology: pass — generated maps match the boundary declarations")
      else
        Mix.shell().error(
          "topology: FAIL — #{Enum.join(stale, ", ")} diverge(s) from the `use Boundary` " <>
            "declarations. Run `mix lcars.topology` (and declare a layer for any new domain in @layers)."
        )

        exit({:shutdown, 1})
      end
    else
      Enum.each(outputs, fn {file, section} -> write_section(file, section) end)
      Mix.shell().info("topology: #{Enum.map_join(outputs, ", ", &elem(&1, 0))} regenerated")
    end
  end

  # ── derivation ────────────────────────────────────────────────────────────

  # Domain boundaries = TOP-LEVEL `use Boundary` declarations. Skipped: `classify_to:`
  # (mix tasks classified into a domain) and SUB-boundaries (a boundary whose module name
  # is prefixed by another boundary, e.g. `Fleet.Pilot.ForgeClient` under `Fleet.Pilot` —
  # an intra-domain wall, not a floor of the ladder).
  defp parse_boundaries do
    all =
      for f <- Path.wildcard("lib/fleet/**/*.ex") ++ ["lib/fleet.ex"],
          File.exists?(f),
          src = File.read!(f),
          String.contains?(src, "use Boundary"),
          not String.contains?(src, "classify_to:"),
          [_, mod] <- [Regex.run(~r/defmodule\s+([\w.]+)/, src)],
          into: %{} do
        deps =
          case Regex.run(~r/use Boundary,.*?deps:\s*\[(.*?)\]/s, src) do
            [_, body] -> Regex.scan(~r/Fleet[\w.]*/, body) |> List.flatten() |> Enum.uniq()
            nil -> []
          end

        {mod, deps -- [mod]}
      end

    mods = Map.keys(all)

    all
    |> Enum.reject(fn {mod, _} -> Enum.any?(mods, &String.starts_with?(mod, &1 <> ".")) end)
    |> Map.new(fn {mod, deps} -> {mod, Enum.filter(deps, &(&1 in mods))} end)
  end

  defp compute_heights(graph) do
    heights =
      Enum.reduce(Map.keys(graph), %{}, fn mod, acc -> elem(height(mod, graph, acc), 1) end)

    Enum.group_by(Map.keys(graph), &Map.fetch!(heights, &1))
  end

  defp height(mod, graph, acc) do
    case acc do
      %{^mod => h} ->
        {h, acc}

      _ ->
        {h, acc} =
          case Map.get(graph, mod, []) |> Enum.filter(&Map.has_key?(graph, &1)) do
            [] ->
              {0, acc}

            deps ->
              Enum.reduce(deps, {-1, acc}, fn d, {mx, a} ->
                {hd, a2} = height(d, graph, a)
                {max(mx, hd), a2}
              end)
              |> then(fn {mx, a} -> {mx + 1, a} end)
          end

        {h, Map.put(acc, mod, h)}
    end
  end

  # ── rendering ─────────────────────────────────────────────────────────────

  # Same organizing axis as the mermaid (layers, top-down) so the two projections read
  # symmetrically; H stays as per-domain data — a layer is NOT a homogeneous height
  # (pod composition spans H3–H4, surface H5–H7), the table shows that honestly.
  defp render_section(by_height) do
    heights = Enum.flat_map(by_height, fn {h, ms} -> Enum.map(ms, &{&1, h}) end) |> Map.new()

    rows =
      heights
      |> Map.keys()
      |> Enum.group_by(fn m ->
        Map.get(@layers, m) || raise "no layer declared in @layers for #{m}"
      end)
      |> Enum.sort_by(fn {_l, ms} -> ms |> Enum.map(&Map.fetch!(heights, &1)) |> Enum.max() end, :desc)
      |> Enum.flat_map(fn {layer, mods} ->
        mods
        |> Enum.sort_by(&{Map.fetch!(heights, &1), &1})
        |> Enum.map(fn m -> "| #{layer} | `#{m}` | #{Map.fetch!(heights, m)} |" end)
      end)

    Enum.join(
      [
        @begin_marker,
        "",
        "Derived from the `use Boundary` declarations (enforced at compile time; this table",
        "is a projection — `mix lcars.topology` regenerates it, the gate refuses divergence).",
        "Layers top-down, same order as the root README diagram. H = 1 + max H of declared",
        "deps; 0 = `deps: []` (pure foundation). Runtime seams (config-injected,",
        "compile-invisible) are NOT in this table — see the \"Seams runtime\" section of `CLAUDE.md`.",
        "",
        "| Layer | Domain | H |",
        "|-------|--------|---|"
      ] ++ rows ++ [@end_marker],
      "\n"
    )
  end

  # Mermaid projection for the root README (the repo's showcase): one subgraph per layer
  # (ordered bottom-up by max height), solid edges = declared compile deps BETWEEN non-foundation
  # domains (foundation edges omitted for readability — every domain may depend down on
  # foundation), dotted edges = the runtime seams declared in @seams.
  defp render_mermaid(graph) do
    heights = graph |> compute_heights() |> Enum.flat_map(fn {h, ms} -> Enum.map(ms, &{&1, h}) end) |> Map.new()
    foundation = for {m, []} <- graph, do: m
    id = fn m -> String.replace(m, ".", "_") end

    # Omitted from the drawing: foundation (everyone may depend down on it) and the OTP root
    # (it starts every domain — 9 edges of pure noise). Both are named in the caption.
    hidden = foundation ++ ["Fleet.Application"]

    layer_groups =
      graph
      |> Map.keys()
      |> Enum.reject(&(&1 in hidden))
      |> Enum.group_by(&Map.fetch!(@layers, &1))
      |> Enum.sort_by(fn {_l, ms} -> ms |> Enum.map(&Map.fetch!(heights, &1)) |> Enum.max() end, :desc)

    subgraphs =
      Enum.flat_map(layer_groups, fn {layer, mods} ->
        ["    subgraph #{String.replace(layer, ~r/\W/, "_")}[\"#{layer}\"]"] ++
          Enum.map(Enum.sort(mods), fn m -> "        #{id.(m)}[\"#{m}\"]" end) ++ ["    end"]
      end)

    edges =
      for {m, deps} <- Enum.sort(graph),
          m not in hidden,
          d <- Enum.sort(deps),
          d not in hidden,
          do: "    #{id.(m)} --> #{id.(d)}"

    seams =
      for {from, to, label} <- @seams, do: "    #{id.(from)} -. \"seam #{label}\" .-> #{id.(to)}"

    Enum.join(
      [@begin_marker, "```mermaid", "flowchart TB"] ++
        subgraphs ++
        edges ++
        seams ++
        [
          "```",
          "",
          "*(Generated by `mix lcars.topology` from the `use Boundary` declarations — the gate",
          "refuses divergence. Omitted for readability: the foundation utilities (`deps: []`: " <>
            Enum.map_join(Enum.sort(foundation), ", ", &"`#{&1}`") <>
            "), which every domain may depend down on, and the OTP root `Fleet.Application`,",
          "which starts every domain. Dotted = runtime seams, config-injected — deliberately",
          "invisible to the compiler, cf. `CLAUDE.md`. The full layered table lives in",
          "`lib/fleet/README.md`.)*"
        ] ++ [@end_marker],
      "\n"
    )
  end

  defp extract_section(content) do
    with [_, rest] <- String.split(content, @begin_marker, parts: 2),
         [body, _] <- String.split(rest, @end_marker, parts: 2) do
      @begin_marker <> body <> @end_marker
    else
      _ -> nil
    end
  end

  defp write_section(file, section) do
    content = File.read!(file)

    case extract_section(content) do
      nil -> Mix.raise("markers not found in #{file} — restore them before regenerating")
      old -> File.write!(file, String.replace(content, old, section))
    end
  end
end
