defmodule Mix.Tasks.Lcars.Topology do
  use Boundary, classify_to: Fleet.Application

  @shortdoc "Regenerates (or --check) the boundary topology map in lib/fleet/README.md"

  @moduledoc """
  Boundary topology map — derives the layered view of the fleet from the `use Boundary`
  declarations (the single source of truth of the dependency structure; the compiler
  enforces it, this task only PROJECTS it) and writes it as a markdown table between
  markers in `lib/fleet/README.md`.

  Height is mechanical: `H(domain) = 1 + max(H(deps))`, 0 for `deps: []` (a DAG —
  boundary forbids cycles — always induces this ladder). The layer NAMES are editorial
  and live in ONE place: `@layers` below. A new or moved domain without a matching
  entry fails the check — changing floor is a conscious, reviewed event, never silent.

  ## Usage

      mix lcars.topology            # regenerate the section in lib/fleet/README.md
      mix lcars.topology --check    # exit 1 if the committed map diverges (gate step)
  """

  use Mix.Task

  @recursive false

  @readme "lib/fleet/README.md"
  @begin_marker "<!-- boundary-topology:begin (generated by `mix lcars.topology` — do not edit by hand) -->"
  @end_marker "<!-- boundary-topology:end -->"

  # Editorial layer names — the ONLY place they are declared. Keys are domain module
  # names as declared in `use Boundary`. "foundation" is the one mechanically checkable
  # name (deps: []); the others are a reading, kept honest by living here alone.
  @layers %{
    "Fleet.Slug" => "foundation",
    "Fleet.EnvParse" => "foundation",
    "Fleet.GitRef" => "foundation",
    "Fleet.Layout" => "foundation",
    "Fleet.Event" => "foundation",
    "Fleet.SchemaCache" => "foundation",
    "Fleet.Labels" => "foundation",
    "Fleet.Decision" => "foundation",
    "Fleet.Shutdown.Quiesce" => "foundation",
    "Fleet.EventRouter" => "substrate",
    "Fleet.CapProfile" => "substrate",
    "Fleet.Credentials" => "pod primitives",
    "Fleet.TaskQueue" => "pod primitives",
    "Fleet.SPBuilder" => "pod primitives",
    "Fleet.Coord" => "pod primitives",
    "Fleet.ProjectBootstrap" => "pod composition",
    "Fleet.Spawner" => "pod composition",
    "Fleet.Workflow" => "work",
    "Fleet.MCP" => "work",
    "Fleet.Observation" => "surface",
    "Fleet.Pilot" => "steering",
    "Fleet.Starfleet" => "steering",
    "Fleet.API" => "surface",
    "Fleet.Application" => "OTP root"
  }

  @impl Mix.Task
  def run(args) do
    check? = "--check" in args

    section = render_section(compute_heights(parse_boundaries()))

    if check? do
      current = File.read!(@readme)

      if extract_section(current) == section do
        Mix.shell().info("topology: pass — #{@readme} matches the boundary declarations")
      else
        Mix.shell().error(
          "topology: FAIL — #{@readme} diverges from the `use Boundary` declarations.\n" <>
            "Run `mix lcars.topology` (and declare a layer for any new domain in @layers)."
        )

        exit({:shutdown, 1})
      end
    else
      write_section(section)
      Mix.shell().info("topology: #{@readme} regenerated")
    end
  end

  # ── derivation ────────────────────────────────────────────────────────────

  # Domain boundaries = TOP-LEVEL `use Boundary` declarations. Skipped: `classify_to:`
  # (mix tasks classified into a domain) and SUB-boundaries (a boundary whose module name
  # is prefixed by another boundary, e.g. `Fleet.Pilot.ForgeClient` under `Fleet.Pilot` —
  # an intra-domain wall, not a floor of the ladder).
  defp parse_boundaries do
    all =
      for f <- Path.wildcard("lib/fleet/**/*.ex") ++ ["lib/fleet.ex"],
          File.exists?(f),
          src = File.read!(f),
          String.contains?(src, "use Boundary"),
          not String.contains?(src, "classify_to:"),
          [_, mod] <- [Regex.run(~r/defmodule\s+([\w.]+)/, src)],
          into: %{} do
        deps =
          case Regex.run(~r/use Boundary,.*?deps:\s*\[(.*?)\]/s, src) do
            [_, body] -> Regex.scan(~r/Fleet[\w.]*/, body) |> List.flatten() |> Enum.uniq()
            nil -> []
          end

        {mod, deps -- [mod]}
      end

    mods = Map.keys(all)

    all
    |> Enum.reject(fn {mod, _} -> Enum.any?(mods, &String.starts_with?(mod, &1 <> ".")) end)
    |> Map.new(fn {mod, deps} -> {mod, Enum.filter(deps, &(&1 in mods))} end)
  end

  defp compute_heights(graph) do
    heights =
      Enum.reduce(Map.keys(graph), %{}, fn mod, acc -> elem(height(mod, graph, acc), 1) end)

    Enum.group_by(Map.keys(graph), &Map.fetch!(heights, &1))
  end

  defp height(mod, graph, acc) do
    case acc do
      %{^mod => h} ->
        {h, acc}

      _ ->
        {h, acc} =
          case Map.get(graph, mod, []) |> Enum.filter(&Map.has_key?(graph, &1)) do
            [] ->
              {0, acc}

            deps ->
              Enum.reduce(deps, {-1, acc}, fn d, {mx, a} ->
                {hd, a2} = height(d, graph, a)
                {max(mx, hd), a2}
              end)
              |> then(fn {mx, a} -> {mx + 1, a} end)
          end

        {h, Map.put(acc, mod, h)}
    end
  end

  # ── rendering ─────────────────────────────────────────────────────────────

  defp render_section(by_height) do
    rows =
      by_height
      |> Enum.sort()
      |> Enum.flat_map(fn {h, mods} ->
        mods
        |> Enum.sort()
        |> Enum.map(fn m ->
          layer = Map.get(@layers, m) || raise "no layer declared in @layers for #{m}"
          "| #{h} | `#{m}` | #{layer} |"
        end)
      end)

    Enum.join(
      [
        @begin_marker,
        "",
        "Derived from the `use Boundary` declarations (enforced at compile time; this table",
        "is a projection — `mix lcars.topology` regenerates it, the gate refuses divergence).",
        "Height = 1 + max height of declared deps; 0 = `deps: []` (pure foundation).",
        "Runtime seams (config-injected, compile-invisible) are NOT in this table — see the",
        "\"Seams runtime\" section of `CLAUDE.md`.",
        "",
        "| H | Domain | Layer |",
        "|---|--------|-------|"
      ] ++ rows ++ [@end_marker],
      "\n"
    )
  end

  defp extract_section(content) do
    with [_, rest] <- String.split(content, @begin_marker, parts: 2),
         [body, _] <- String.split(rest, @end_marker, parts: 2) do
      @begin_marker <> body <> @end_marker
    else
      _ -> nil
    end
  end

  defp write_section(section) do
    content = File.read!(@readme)

    case extract_section(content) do
      nil -> Mix.raise("markers not found in #{@readme} — restore them before regenerating")
      old -> File.write!(@readme, String.replace(content, old, section))
    end
  end
end
