defmodule Mix.Tasks.Lcars.Topology do
  use Boundary, classify_to: Fleet.Application

  @shortdoc "Regenerates (or --check) the boundary topology map in lib/fleet/README.md"

  @moduledoc """
  Boundary topology map — derives the layered view of the fleet from the `use Boundary`
  declarations (the single source of truth of the dependency structure; the compiler
  enforces it, this task only PROJECTS it) and writes it as a markdown table between
  markers in `lib/fleet/README.md`.

  The projection reads Boundary's COMPILED graph (`Boundary.all/1` over
  `Boundary.Mix.View.build/0`), not our source text. It therefore shows what the compiler actually
  enforces, which is the only thing worth comparing a committed map against.

  ⚠ NOT A REGEX OVER THE SOURCE, and that is the whole reason: such a regex IS a mechanism that
  always says YES. A `deps:` list containing a COMMENT with a `[]` in it truncates the capture at
  that bracket, and every dependency declared after it vanishes — a real shape, on a real domain
  whose declared dependency on a foundation module never reaches the extractor.

  And it produces no VISIBLE error, for a reason worth stating because it is LUCK rather than
  design: this table renders `H`, not dep lists, and `H = 1 + max(H(deps))` — a lost `deps: []`
  foundation sits at height 0, so dropping it cannot move a height. A lost dep of NON-zero height
  would shift a floor with nothing to catch it. The extractor would be wrong and the projection
  would happen to absorb it.

  The price is one function: `Boundary.Mix.View.build/0` is `@moduledoc false`, a private entry point
  of the dependency (everything after it — `Boundary.all/1`, the `%Boundary{}` fields — is public and
  specified). If a boundary upgrade moves it, this task raises at gate time. That is the GOOD failure:
  loud, immediate, and it sends someone to look. The alternative is a hand-rolled parser that fails
  silently and stays green — which is the defect this project exists to remove. We already depend on
  boundary totally: `mix compile --warnings-as-errors` refuses the build on a violation. Reading its
  graph adds no dependency, it stops re-deriving one by hand.

  Height is mechanical: `H(domain) = 1 + max(H(deps))`, 0 for `deps: []` (a DAG —
  boundary forbids cycles — always induces this ladder). The layer NAMES are editorial
  and live in ONE place: `@layers` below. A new or moved domain without a matching
  entry fails the check — changing floor is a conscious, reviewed event, never silent.

  ## Usage

      mix lcars.topology            # regenerate the section in lib/fleet/README.md
      mix lcars.topology --check    # exit 1 if the committed map diverges (gate step)
  """

  use Mix.Task

  @recursive false

  @readme "lib/fleet/README.md"
  @root_readme "README.md"
  @begin_marker "<!-- boundary-topology:begin (generated by `mix lcars.topology` — do not edit by hand) -->"
  @end_marker "<!-- boundary-topology:end -->"

  # UPWARD runtime seams (config-injected, compile-INVISIBLE — they cannot be derived from
  # the boundary declarations, which is the point: boundary forbids the literal edge). Declared
  # here so the generated diagram can draw them dotted; the contract lives in CLAUDE.md § Seams.
  # NOT listed: injection seams over an EXISTING compile dep (`:coord_backend`, `:launch_backend`)
  # — those swap an implementation for hermeticity, they do not cross a forbidden edge.
  @seams [
    {"Fleet.Spawner", "Fleet.MCP", ":mcp_socket_provisioner"},
    # NOT here, and the test says why: `:forge_client` and `:project_onboard` reach targets that
    # sit BELOW MCP, so their edges are ordinary compile deps the boundary checker holds. Those
    # seams exist — they are how a test injects a stub — but as INJECTION over a DECLARED dep, the
    # class this table does not draw (same as `:coord_backend`, cf. CLAUDE.md § Seams).
    {"Fleet.MCP", "Fleet.Pilot", ":pod_reaper"},
    # LISTED, and the near-miss is worth naming: filing this one "same shape as `:coord_backend`"
    # puts it in the class excluded just above and drops it from the table. THE TEST IS THE `deps:`
    # LIST, NOT THE INJECTION MECHANISM — `Fleet.Pilot` is not in Admiral's deps, so this crosses an
    # edge boundary forbids and belongs here.
    {"Fleet.Admiral", "Fleet.Pilot", ":admiral_completion_inflight_fun"}
  ]

  # Editorial layer names — the ONLY place they are declared. Keys are domain module
  # names as declared in `use Boundary`. "foundation" is the one mechanically checkable
  # name (deps: []); the others are a reading, kept honest by living here alone.
  @layers %{
    "Fleet.Slug" => "foundation",
    "Fleet.EnvParse" => "foundation",
    # A1 — container-wide admin settings reader (/etc/lcars/fleet.json), pure like its
    # neighbour EnvParse: deps [], read once by runtime.exs at boot.
    "Fleet.SystemConfig" => "foundation",
    "Fleet.GitRef" => "foundation",
    "Fleet.Layout" => "foundation",
    "Fleet.PodId" => "foundation",
    "Fleet.Catalogue" => "foundation",
    "Fleet.ReceptionFilter" => "foundation",
    "Fleet.DurableLog" => "foundation",
    "Fleet.Event" => "foundation",
    "Fleet.SchemaCache" => "foundation",
    "Fleet.Labels" => "foundation",
    "Fleet.Toolchain" => "foundation",
    "Fleet.Conflict" => "foundation",
    # C2 — the judge's machine verdict on the wire (render into a review body,
    # read it back). Pure text <-> map like Conflict, and foundation for the same reason: its two
    # ends are Fleet.Pilot (writes) and Fleet.Forge (reads), which cannot see each other.
    "Fleet.FindingsWire" => "foundation",
    "Fleet.Shutdown.Quiesce" => "foundation",
    "Fleet.Publish.InFlight" => "foundation",
    "Fleet.Opts" => "foundation",
    "Fleet.Grace" => "foundation",
    "Fleet.PeriodicCheck" => "foundation",
    "Fleet.ReleaseDoor" => "foundation",
    "Fleet.EventRouter" => "substrate",
    "Fleet.CapProfile" => "substrate",
    "Fleet.Credentials" => "pod primitives",
    "Fleet.TaskQueue" => "pod primitives",
    "Fleet.SPBuilder" => "pod primitives",
    "Fleet.ProjectBootstrap" => "pod composition",
    "Fleet.Spawner" => "pod composition",
    "Fleet.Workflow" => "work",
    # The project LIFECYCLE — what a project is (onboarding, card, roles, architect, worktrees) —
    # as opposed to the rail that drives it afterwards. It sits at `work` and NOT at `steering`
    # deliberately: MCP declares a plain dep on it, which is the whole point of the extraction (the
    # `:project_onboard` upward seam existed only because this code sat above MCP).
    "Fleet.Project" => "work",
    # The forge sits ABOVE work and BELOW steering: the pilot drives it, it drives nothing. Its
    # floor is what makes "one HTTP exit" compiled rather than conventional — `Req` is fenced to
    # this boundary alone.
    "Fleet.Forge" => "work",
    "Fleet.MCP" => "work",
    # La PROJECTION du roster de forge d'un catalogue. Son etage se deduit de sa plus haute dep :
    # `Fleet.Credentials` (pod primitives), donc elle est au-dessus. Ni composition de pod, ni
    # pilotage — elle ne tourne pas au runtime : elle est lue par les portes CLI et par le gate.
    # `work` est le premier etage qui la contienne honnetement, avec ses voisins qui dependent
    # eux aussi de Credentials. La ranger sous le boot la mettrait au SOMMET du graphe sans qu'elle
    # soit du code de boot.
    "Fleet.Roster" => "work",
    "Fleet.Observation" => "surface",
    "Fleet.Pilot" => "steering",
    "Fleet.Admiral" => "steering",
    "Fleet.API" => "surface",
    "Fleet.Application" => "OTP root"
  }

  @impl Mix.Task
  def run(args) do
    check? = "--check" in args

    graph = parse_boundaries()

    outputs = [
      {@readme, render_section(compute_heights(graph))},
      {@root_readme, render_mermaid(graph)}
    ]

    if check? do
      stale =
        for {file, section} <- outputs, extract_section(File.read!(file)) != section, do: file

      if stale == [] do
        Mix.shell().info("topology: pass — generated maps match the boundary declarations")
      else
        Mix.shell().error(
          "topology: FAIL — #{Enum.join(stale, ", ")} diverge(s) from the `use Boundary` " <>
            "declarations. Run `mix lcars.topology` (and declare a layer for any new domain in @layers)."
        )

        exit({:shutdown, 1})
      end
    else
      Enum.each(outputs, fn {file, section} -> write_section(file, section) end)
      Mix.shell().info("topology: #{Enum.map_join(outputs, ", ", &elem(&1, 0))} regenerated")
    end
  end

  # ── derivation ────────────────────────────────────────────────────────────

  # Domain boundaries = TOP-LEVEL boundaries of `:lcars_fleet` declared under `lib/`. Excluded, in
  # this order: another app's boundaries; boundaries compiled from `test/support` (they exist in the
  # `:test` env the gate runs in, and are not runtime topology); SUB-boundaries (a boundary whose
  # module name is prefixed by another one, e.g. `Fleet.Forge.Client` under `Fleet.Pilot` — an
  # intra-domain wall, not a floor of the ladder). `classify_to:` needs no filter here: a module
  # classified INTO a domain is not a boundary of its own in the compiled graph.
  defp parse_boundaries do
    lib_boundaries =
      Boundary.Mix.View.build()
      |> Boundary.all()
      |> Enum.filter(&(&1.app == :lcars_fleet and lib_source?(&1.name)))

    names = MapSet.new(lib_boundaries, & &1.name)

    top =
      Enum.reject(lib_boundaries, fn b ->
        Enum.any?(
          names,
          &(&1 != b.name and String.starts_with?(inspect(b.name), inspect(&1) <> "."))
        )
      end)

    top_names = MapSet.new(top, & &1.name)

    Map.new(top, fn b ->
      deps =
        b.deps
        |> Enum.map(fn {mod, _mode} -> mod end)
        |> Enum.filter(&MapSet.member?(top_names, &1))
        |> Enum.map(&inspect/1)
        |> Enum.uniq()

      {inspect(b.name), deps}
    end)
  end

  # A boundary's own compiled-from path. `test/support` modules are boundaries too in the `:test` env
  # (the env the gate runs in) — they are not part of the runtime topology.
  defp lib_source?(module) do
    case module.module_info(:compile)[:source] do
      nil -> false
      source -> source |> List.to_string() |> String.contains?("/lib/")
    end
  end

  defp compute_heights(graph) do
    heights =
      Enum.reduce(Map.keys(graph), %{}, fn mod, acc -> elem(height(mod, graph, acc), 1) end)

    Enum.group_by(Map.keys(graph), &Map.fetch!(heights, &1))
  end

  defp height(mod, graph, acc) do
    case acc do
      %{^mod => h} ->
        {h, acc}

      _ ->
        {h, acc} =
          case Map.get(graph, mod, []) |> Enum.filter(&Map.has_key?(graph, &1)) do
            [] ->
              {0, acc}

            deps ->
              Enum.reduce(deps, {-1, acc}, fn d, {mx, a} ->
                {hd, a2} = height(d, graph, a)
                {max(mx, hd), a2}
              end)
              |> then(fn {mx, a} -> {mx + 1, a} end)
          end

        {h, Map.put(acc, mod, h)}
    end
  end

  # ── rendering ─────────────────────────────────────────────────────────────

  # Same organizing axis as the mermaid (layers, top-down) so the two projections read
  # symmetrically; H stays as per-domain data — a layer is NOT a homogeneous height
  # (pod composition spans H3–H4, surface H5–H7), the table shows that honestly.
  defp render_section(by_height) do
    heights = Enum.flat_map(by_height, fn {h, ms} -> Enum.map(ms, &{&1, h}) end) |> Map.new()

    rows =
      heights
      |> Map.keys()
      |> Enum.group_by(fn m ->
        Map.get(@layers, m) || raise "no layer declared in @layers for #{m}"
      end)
      |> Enum.sort_by(
        fn {_l, ms} -> ms |> Enum.map(&Map.fetch!(heights, &1)) |> Enum.max() end,
        :desc
      )
      |> Enum.flat_map(fn {layer, mods} ->
        mods
        |> Enum.sort_by(&{Map.fetch!(heights, &1), &1})
        |> Enum.map(fn m -> "| #{layer} | `#{m}` | #{Map.fetch!(heights, m)} |" end)
      end)

    Enum.join(
      [
        @begin_marker,
        "",
        "Derived from the `use Boundary` declarations (enforced at compile time; this table",
        "is a projection — `mix lcars.topology` regenerates it, the gate refuses divergence).",
        "Layers top-down, same order as the root README diagram. H = 1 + max H of declared",
        "deps; 0 = `deps: []` (pure foundation). Runtime seams (config-injected,",
        "compile-invisible) are NOT in this table — see the \"Seams runtime\" section of `CLAUDE.md`.",
        "",
        "| Layer | Domain | H |",
        "|-------|--------|---|"
      ] ++ rows ++ [@end_marker],
      "\n"
    )
  end

  # Mermaid projection for the root README (the repo's showcase): one subgraph per layer
  # (ordered bottom-up by max height), solid edges = declared compile deps BETWEEN non-foundation
  # domains (foundation edges omitted for readability — every domain may depend down on
  # foundation), dotted edges = the runtime seams declared in @seams.
  defp render_mermaid(graph) do
    heights =
      graph
      |> compute_heights()
      |> Enum.flat_map(fn {h, ms} -> Enum.map(ms, &{&1, h}) end)
      |> Map.new()

    foundation = for {m, []} <- graph, do: m
    id = fn m -> String.replace(m, ".", "_") end

    # Omitted from the drawing: foundation (everyone may depend down on it) and the OTP root
    # (it starts every domain — 9 edges of pure noise). Both are named in the caption.
    hidden = foundation ++ ["Fleet.Application"]

    layer_groups =
      graph
      |> Map.keys()
      |> Enum.reject(&(&1 in hidden))
      |> Enum.group_by(&Map.fetch!(@layers, &1))
      |> Enum.sort_by(
        fn {_l, ms} -> ms |> Enum.map(&Map.fetch!(heights, &1)) |> Enum.max() end,
        :desc
      )

    subgraphs =
      Enum.flat_map(layer_groups, fn {layer, mods} ->
        ["    subgraph #{String.replace(layer, ~r/\W/, "_")}[\"#{layer}\"]"] ++
          Enum.map(Enum.sort(mods), fn m -> "        #{id.(m)}[\"#{m}\"]" end) ++ ["    end"]
      end)

    edges =
      for {m, deps} <- Enum.sort(graph),
          m not in hidden,
          d <- Enum.sort(deps),
          d not in hidden,
          do: "    #{id.(m)} --> #{id.(d)}"

    seams =
      for {from, to, label} <- @seams, do: "    #{id.(from)} -. \"seam #{label}\" .-> #{id.(to)}"

    Enum.join(
      [@begin_marker, "```mermaid", "flowchart TB"] ++
        subgraphs ++
        edges ++
        seams ++
        [
          "```",
          "",
          "*(Generated by `mix lcars.topology` from the `use Boundary` declarations — the gate",
          "refuses divergence. Omitted for readability: the foundation utilities (`deps: []`: " <>
            Enum.map_join(Enum.sort(foundation), ", ", &"`#{&1}`") <>
            "), which every domain may depend down on, and the OTP root `Fleet.Application`,",
          "which starts every domain. Dotted = runtime seams, config-injected — deliberately",
          "invisible to the compiler, cf. `CLAUDE.md`. The full layered table lives in",
          "`lib/fleet/README.md`.)*"
        ] ++ [@end_marker],
      "\n"
    )
  end

  defp extract_section(content) do
    with [_, rest] <- String.split(content, @begin_marker, parts: 2),
         [body, _] <- String.split(rest, @end_marker, parts: 2) do
      @begin_marker <> body <> @end_marker
    else
      _ -> nil
    end
  end

  defp write_section(file, section) do
    content = File.read!(file)

    case extract_section(content) do
      nil -> Mix.raise("markers not found in #{file} — restore them before regenerating")
      old -> File.write!(file, String.replace(content, old, section))
    end
  end
end
