defmodule Mix.Tasks.Lcars.Topology do
  use Boundary, classify_to: Fleet.Application

  @shortdoc "Regenerates (or --check) the boundary topology map in lib/fleet/README.md"

  @moduledoc """
  Projects the compiled Boundary graph into marked sections of lib/fleet/README.md
  and README.md, relative to runtime/.

    mix lcars.topology
    mix lcars.topology --check  # exit 1 when either section is stale

  The graph comes from Boundary.Mix.View.build/0, a private dependency API whose
  removal will break this task. A source regex previously lost dependencies at
  brackets inside comments; reading the compiled graph avoids that ambiguity.

  Only top-level application boundaries with a compile path containing /lib/
  and their direct dependencies on other selected boundaries are included.
  Height is zero for no included dependencies, otherwise one above the maximum
  dependency height. It does not establish purity.

  Layer names are editorial in @layers; missing entries raise, but moving an
  existing domain does not force a layer change. Runtime seams are declared
  separately because injected calls do not appear in the compiled graph.
  """

  use Mix.Task

  @recursive false

  @readme "lib/fleet/README.md"
  @root_readme "README.md"
  @begin_marker "<!-- boundary-topology:begin (generated by `mix lcars.topology` — do not edit by hand) -->"
  @end_marker "<!-- boundary-topology:end -->"

  # Dotted edges cross absent compile dependencies; see CLAUDE.md, Seams.
  # Injection over an existing dependency (e.g. :coord_backend) is omitted.
  @seams [
    {"Fleet.Spawner", "Fleet.MCP", ":mcp_socket_provisioner"},
    {"Fleet.MCP", "Fleet.Pilot", ":pod_reaper"},
    # Admiral has no Pilot dependency; this injection crosses that boundary.
    {"Fleet.Admiral", "Fleet.Pilot", ":admiral_completion_inflight_fun"}
  ]

  # Editorial grouping; heights are derived independently.
  @layers %{
    "Fleet.Slug" => "foundation",
    "Fleet.EnvParse" => "foundation",
    "Fleet.SystemConfig" => "foundation",
    "Fleet.GitRef" => "foundation",
    "Fleet.Layout" => "foundation",
    "Fleet.BootGuard" => "foundation",
    "Fleet.PodId" => "foundation",
    "Fleet.Catalogue" => "foundation",
    "Fleet.ReceptionFilter" => "foundation",
    "Fleet.DurableLog" => "foundation",
    "Fleet.Event" => "foundation",
    "Fleet.SchemaCache" => "foundation",
    "Fleet.Labels" => "foundation",
    "Fleet.Toolchain" => "foundation",
    "Fleet.Conflict" => "foundation",
    "Fleet.FindingsWire" => "foundation",
    "Fleet.Shutdown.Quiesce" => "foundation",
    "Fleet.Publish.InFlight" => "foundation",
    "Fleet.Opts" => "foundation",
    "Fleet.Grace" => "foundation",
    "Fleet.PeriodicCheck" => "foundation",
    "Fleet.ReleaseDoor" => "foundation",
    "Fleet.EventRouter" => "substrate",
    "Fleet.CapProfile" => "substrate",
    "Fleet.Credentials" => "pod primitives",
    "Fleet.TaskQueue" => "pod primitives",
    "Fleet.SPBuilder" => "pod primitives",
    "Fleet.ProjectBootstrap" => "pod composition",
    "Fleet.Spawner" => "pod composition",
    "Fleet.Workflow" => "work",
    "Fleet.Project" => "work",
    "Fleet.Forge" => "work",
    "Fleet.MCP" => "work",
    "Fleet.Roster" => "work",
    "Fleet.Observation" => "surface",
    "Fleet.Pilot" => "steering",
    "Fleet.Admiral" => "steering",
    "Fleet.API" => "surface",
    "Fleet.Application" => "OTP root"
  }

  @impl Mix.Task
  def run(args) do
    check? = "--check" in args

    graph = parse_boundaries()

    outputs = [
      {@readme, render_section(compute_heights(graph))},
      {@root_readme, render_mermaid(graph)}
    ]

    if check? do
      stale =
        for {file, section} <- outputs, extract_section(File.read!(file)) != section, do: file

      if stale == [] do
        Mix.shell().info("topology: pass — generated maps match the boundary declarations")
      else
        Mix.shell().error(
          "topology: FAIL — #{Enum.join(stale, ", ")} diverge(s) from the `use Boundary` " <>
            "declarations. Run `mix lcars.topology` (and declare a layer for any new domain in @layers)."
        )

        exit({:shutdown, 1})
      end
    else
      Enum.each(outputs, fn {file, section} -> write_section(file, section) end)
      Mix.shell().info("topology: #{Enum.map_join(outputs, ", ", &elem(&1, 0))} regenerated")
    end
  end

  # Namespace descendants are omitted, not folded into their parent.
  defp parse_boundaries do
    lib_boundaries =
      Boundary.Mix.View.build()
      |> Boundary.all()
      |> Enum.filter(&(&1.app == :lcars_fleet and lib_source?(&1.name)))

    names = MapSet.new(lib_boundaries, & &1.name)

    top =
      Enum.reject(lib_boundaries, fn b ->
        Enum.any?(
          names,
          &(&1 != b.name and String.starts_with?(inspect(b.name), inspect(&1) <> "."))
        )
      end)

    top_names = MapSet.new(top, & &1.name)

    Map.new(top, fn b ->
      deps =
        b.deps
        |> Enum.map(fn {mod, _mode} -> mod end)
        |> Enum.filter(&MapSet.member?(top_names, &1))
        |> Enum.map(&inspect/1)
        |> Enum.uniq()

      {inspect(b.name), deps}
    end)
  end

  # Test-support boundaries must not enter the runtime graph.
  defp lib_source?(module) do
    case module.module_info(:compile)[:source] do
      nil -> false
      source -> source |> List.to_string() |> String.contains?("/lib/")
    end
  end

  defp compute_heights(graph) do
    heights =
      Enum.reduce(Map.keys(graph), %{}, fn mod, acc -> elem(height(mod, graph, acc), 1) end)

    Enum.group_by(Map.keys(graph), &Map.fetch!(heights, &1))
  end

  defp height(mod, graph, acc) do
    case acc do
      %{^mod => h} ->
        {h, acc}

      _ ->
        {h, acc} =
          graph
          |> Map.get(mod, [])
          |> Enum.filter(&Map.has_key?(graph, &1))
          |> deps_height(graph, acc)

        {h, Map.put(acc, mod, h)}
    end
  end

  defp deps_height([], _graph, acc), do: {0, acc}

  defp deps_height(deps, graph, acc) do
    {mx, a} =
      Enum.reduce(deps, {-1, acc}, fn d, {mx, a} ->
        {hd, a2} = height(d, graph, a)
        {max(mx, hd), a2}
      end)

    {mx + 1, a}
  end

  # A layer can contain several heights; retain each domain's height in the table.
  defp render_section(by_height) do
    heights = Enum.flat_map(by_height, fn {h, ms} -> Enum.map(ms, &{&1, h}) end) |> Map.new()

    rows =
      heights
      |> Map.keys()
      |> Enum.group_by(fn m ->
        Map.get(@layers, m) || raise "no layer declared in @layers for #{m}"
      end)
      |> Enum.sort_by(
        fn {_l, ms} -> ms |> Enum.map(&Map.fetch!(heights, &1)) |> Enum.max() end,
        :desc
      )
      |> Enum.flat_map(fn {layer, mods} ->
        mods
        |> Enum.sort_by(&{Map.fetch!(heights, &1), &1})
        |> Enum.map(fn m -> "| #{layer} | `#{m}` | #{Map.fetch!(heights, m)} |" end)
      end)

    Enum.join(
      [
        @begin_marker,
        "",
        "Derived from the `use Boundary` declarations (enforced at compile time; this table",
        "is a projection — `mix lcars.topology` regenerates it, the gate refuses divergence).",
        "Layers top-down, same order as the root README diagram. H = 1 + max H of declared",
        "deps; 0 = `deps: []` (pure foundation). Runtime seams (config-injected,",
        "compile-invisible) are NOT in this table — see the \"Seams runtime\" section of `CLAUDE.md`.",
        "",
        "| Layer | Domain | H |",
        "|-------|--------|---|"
      ] ++ rows ++ [@end_marker],
      "\n"
    )
  end

  # Foundation and OTP-root edges are omitted; @seams supplies dotted runtime edges.
  defp render_mermaid(graph) do
    heights =
      graph
      |> compute_heights()
      |> Enum.flat_map(fn {h, ms} -> Enum.map(ms, &{&1, h}) end)
      |> Map.new()

    foundation = for {m, []} <- graph, do: m
    id = fn m -> String.replace(m, ".", "_") end

    hidden = foundation ++ ["Fleet.Application"]

    layer_groups =
      graph
      |> Map.keys()
      |> Enum.reject(&(&1 in hidden))
      |> Enum.group_by(&Map.fetch!(@layers, &1))
      |> Enum.sort_by(
        fn {_l, ms} -> ms |> Enum.map(&Map.fetch!(heights, &1)) |> Enum.max() end,
        :desc
      )

    subgraphs =
      Enum.flat_map(layer_groups, fn {layer, mods} ->
        ["    subgraph #{String.replace(layer, ~r/\W/, "_")}[\"#{layer}\"]"] ++
          Enum.map(Enum.sort(mods), fn m -> "        #{id.(m)}[\"#{m}\"]" end) ++ ["    end"]
      end)

    edges =
      for {m, deps} <- Enum.sort(graph),
          m not in hidden,
          d <- Enum.sort(deps),
          d not in hidden,
          do: "    #{id.(m)} --> #{id.(d)}"

    seams =
      for {from, to, label} <- @seams, do: "    #{id.(from)} -. \"seam #{label}\" .-> #{id.(to)}"

    Enum.join(
      [@begin_marker, "```mermaid", "flowchart TB"] ++
        subgraphs ++
        edges ++
        seams ++
        [
          "```",
          "",
          "*(Generated by `mix lcars.topology` from the `use Boundary` declarations — the gate",
          "refuses divergence. Omitted for readability: the foundation utilities (`deps: []`: " <>
            Enum.map_join(Enum.sort(foundation), ", ", &"`#{&1}`") <>
            "), which every domain may depend down on, and the OTP root `Fleet.Application`,",
          "which starts every domain. Dotted = runtime seams, config-injected — deliberately",
          "invisible to the compiler, cf. `CLAUDE.md`. The full layered table lives in",
          "`lib/fleet/README.md`.)*"
        ] ++ [@end_marker],
      "\n"
    )
  end

  defp extract_section(content) do
    with [_, rest] <- String.split(content, @begin_marker, parts: 2),
         [body, _] <- String.split(rest, @end_marker, parts: 2) do
      @begin_marker <> body <> @end_marker
    else
      _ -> nil
    end
  end

  defp write_section(file, section) do
    content = File.read!(file)

    case extract_section(content) do
      nil -> Mix.raise("markers not found in #{file} — restore them before regenerating")
      old -> File.write!(file, String.replace(content, old, section))
    end
  end
end
